# Generated by Django 4.0.5 on 2022-06-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.CharField(max_length=100, verbose_name='トップ画像'),
        ),
        migrations.AlterField(
            model_name='work',
            name='thumbnail',
            field=models.CharField(max_length=100, verbose_name='サムネイル'),
        ),
    ]
