# Generated by Django 4.0.5 on 2022-06-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_work_image_alter_work_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.CharField(max_length=255, verbose_name='トップ画像URL'),
        ),
        migrations.AlterField(
            model_name='work',
            name='thumbnail',
            field=models.CharField(max_length=255, verbose_name='サムネイルURL'),
        ),
    ]
